import type { Container } from "@/types/container";

export const containers: Container[] = [
  // ── EMBALAJES Y RESIDUOS ESPECIALES ─────────────────────────────────────
  {
    id: "ecopil",
    slug: "ecopil",
    category: "embalajes",
    modelPath: "/models/ecopil.glb",
    posterPath: "/posters/ecopil.webp",
    specs: {
      length: 300,
      width: 300,
      height: 400,
      capacity: "5L",
      weight: 1,
      material: "Plástico",
    },
    nameKey: "catalog.containers.ecopil.name",
    descriptionKey: "catalog.containers.ecopil.description",
    useCasesKey: "catalog.containers.ecopil.useCases",
  },
  {
    id: "fluorescents",
    slug: "fluorescents",
    category: "embalajes",
    modelPath: "/models/fluorescents.glb",
    posterPath: "/posters/fluorescents.webp",
    specs: {
      length: 400,
      width: 400,
      height: 600,
      capacity: "50 unidades",
      weight: 3,
      material: "Cartón / Plástico",
    },
    nameKey: "catalog.containers.fluorescents.name",
    descriptionKey: "catalog.containers.fluorescents.description",
    useCasesKey: "catalog.containers.fluorescents.useCases",
  },
  {
    id: "toners",
    slug: "toners",
    category: "embalajes",
    modelPath: "/models/toners.glb",
    posterPath: "/posters/toners.webp",
    specs: {
      length: 350,
      width: 350,
      height: 500,
      capacity: "20 unidades",
      weight: 2,
      material: "Cartón reforzado",
    },
    nameKey: "catalog.containers.toners.name",
    descriptionKey: "catalog.containers.toners.description",
    useCasesKey: "catalog.containers.toners.useCases",
  },
  {
    id: "ibc-1000l",
    slug: "ibc-1000l",
    category: "embalajes",
    modelPath: "/models/ibc-1000l.glb",
    posterPath: "/posters/ibc-1000l.webp",
    specs: {
      length: 1200,
      width: 1000,
      height: 1160,
      capacity: "1000L",
      weight: 60,
      material: "Polietileno / Acero",
    },
    nameKey: "catalog.containers.ibc-1000l.name",
    descriptionKey: "catalog.containers.ibc-1000l.description",
    useCasesKey: "catalog.containers.ibc-1000l.useCases",
  },
  {
    id: "sac-net",
    slug: "sac-net",
    category: "embalajes",
    modelPath: "/models/sac-net.glb",
    posterPath: "/posters/sac-net.webp",
    specs: {
      length: 900,
      width: 900,
      height: 1200,
      capacity: "1m³",
      weight: 5,
      material: "Malla plástica",
    },
    nameKey: "catalog.containers.sac-net.name",
    descriptionKey: "catalog.containers.sac-net.description",
    useCasesKey: "catalog.containers.sac-net.useCases",
  },
  {
    id: "big-bag",
    slug: "big-bag",
    category: "embalajes",
    modelPath: "/models/big-bag.glb",
    posterPath: "/posters/big-bag.webp",
    specs: {
      length: 900,
      width: 900,
      height: 1100,
      capacity: "1m³",
      weight: 3,
      material: "Polipropileno tejido",
    },
    nameKey: "catalog.containers.big-bag.name",
    descriptionKey: "catalog.containers.big-bag.description",
    useCasesKey: "catalog.containers.big-bag.useCases",
  },
  {
    id: "boxs-bateries",
    slug: "boxs-bateries",
    category: "embalajes",
    modelPath: "/models/boxs-bateries.glb",
    posterPath: "/posters/boxs-bateries.webp",
    specs: {
      length: 600,
      width: 400,
      height: 400,
      capacity: "40kg",
      weight: 3,
      material: "Cartón / EPS",
    },
    nameKey: "catalog.containers.boxs-bateries.name",
    descriptionKey: "catalog.containers.boxs-bateries.description",
    useCasesKey: "catalog.containers.boxs-bateries.useCases",
  },
  {
    id: "sacs-fibrociment",
    slug: "sacs-fibrociment",
    category: "embalajes",
    modelPath: "/models/sacs-fibrociment.glb",
    posterPath: "/posters/sacs-fibrociment.webp",
    specs: {
      length: 1200,
      width: 800,
      height: 200,
      capacity: "200kg",
      weight: 4,
      material: "Polipropileno / Fibra",
    },
    nameKey: "catalog.containers.sacs-fibrociment.name",
    descriptionKey: "catalog.containers.sacs-fibrociment.description",
    useCasesKey: "catalog.containers.sacs-fibrociment.useCases",
  },
  {
    id: "bido-especials",
    slug: "bido-especials",
    category: "embalajes",
    modelPath: "/models/bido-especials.glb",
    posterPath: "/posters/bido-especials.webp",
    specs: {
      length: 600,
      width: 600,
      height: 900,
      capacity: "60-200L",
      weight: 15,
      material: "Acero / Plástico",
    },
    nameKey: "catalog.containers.bido-especials.name",
    descriptionKey: "catalog.containers.bido-especials.description",
    useCasesKey: "catalog.containers.bido-especials.useCases",
  },
  {
    id: "caixa-perillosos",
    slug: "caixa-perillosos",
    category: "embalajes",
    modelPath: "/models/caixa-perillosos.glb",
    posterPath: "/posters/caixa-perillosos.webp",
    specs: {
      length: 600,
      width: 400,
      height: 350,
      capacity: "30kg",
      weight: 5,
      material: "Cartón UN homologado",
    },
    nameKey: "catalog.containers.caixa-perillosos.name",
    descriptionKey: "catalog.containers.caixa-perillosos.description",
    useCasesKey: "catalog.containers.caixa-perillosos.useCases",
  },
  // ── CONTENEDORES ─────────────────────────────────────────────────────────
  {
    id: "plastic-240l",
    slug: "plastic-240l",
    category: "contenedores",
    modelPath: "/models/plastic-240l.glb",
    posterPath: "/posters/plastic-240l.webp",
    specs: {
      length: 730,
      width: 580,
      height: 1070,
      capacity: "240L",
      weight: 25,
      material: "Polietileno",
    },
    nameKey: "catalog.containers.plastic-240l.name",
    descriptionKey: "catalog.containers.plastic-240l.description",
    useCasesKey: "catalog.containers.plastic-240l.useCases",
  },
  {
    id: "selectiva-1100l",
    slug: "selectiva-1100l",
    category: "contenedores",
    modelPath: "/models/selectiva-1100l.glb",
    posterPath: "/posters/selectiva-1100l.webp",
    specs: {
      length: 1370,
      width: 770,
      height: 1380,
      capacity: "1100L",
      weight: 65,
      material: "Polietileno",
    },
    nameKey: "catalog.containers.selectiva-1100l.name",
    descriptionKey: "catalog.containers.selectiva-1100l.description",
    useCasesKey: "catalog.containers.selectiva-1100l.useCases",
  },
  {
    id: "iglu-vidre",
    slug: "iglu-vidre",
    category: "contenedores",
    modelPath: "/models/iglu-vidre.glb",
    posterPath: "/posters/iglu-vidre.webp",
    specs: {
      length: 1800,
      width: 1800,
      height: 1500,
      capacity: "3000L",
      weight: 200,
      material: "Polietileno",
    },
    nameKey: "catalog.containers.iglu-vidre.name",
    descriptionKey: "catalog.containers.iglu-vidre.description",
    useCasesKey: "catalog.containers.iglu-vidre.useCases",
  },
  {
    id: "skip-2m3",
    slug: "skip-2m3",
    category: "contenedores",
    modelPath: "/models/skip-2m3.glb",
    posterPath: "/posters/skip-2m3.webp",
    specs: {
      length: 2000,
      width: 1300,
      height: 800,
      capacity: "2m³",
      weight: 200,
      material: "Acero",
    },
    nameKey: "catalog.containers.skip-2m3.name",
    descriptionKey: "catalog.containers.skip-2m3.description",
    useCasesKey: "catalog.containers.skip-2m3.useCases",
  },
  {
    id: "skip-3m3",
    slug: "skip-3m3",
    category: "contenedores",
    modelPath: "/models/skip-3m3.glb",
    posterPath: "/posters/skip-3m3.webp",
    specs: {
      length: 2500,
      width: 1500,
      height: 1000,
      capacity: "3m³",
      weight: 250,
      material: "Acero",
    },
    nameKey: "catalog.containers.skip-3m3.name",
    descriptionKey: "catalog.containers.skip-3m3.description",
    useCasesKey: "catalog.containers.skip-3m3.useCases",
  },
  {
    id: "skip-5m3",
    slug: "skip-5m3",
    category: "contenedores",
    modelPath: "/models/skip-5m3.glb",
    posterPath: "/posters/skip-5m3.webp",
    specs: {
      length: 3000,
      width: 1700,
      height: 1200,
      capacity: "5m³",
      weight: 350,
      material: "Acero",
    },
    nameKey: "catalog.containers.skip-5m3.name",
    descriptionKey: "catalog.containers.skip-5m3.description",
    useCasesKey: "catalog.containers.skip-5m3.useCases",
  },
  {
    id: "skip-6m3-tapat",
    slug: "skip-6m3-tapat",
    category: "contenedores",
    modelPath: "/models/skip-6m3-tapat.glb",
    posterPath: "/posters/skip-6m3-tapat.webp",
    specs: {
      length: 3200,
      width: 1800,
      height: 1400,
      capacity: "6m³",
      weight: 420,
      material: "Acero",
    },
    nameKey: "catalog.containers.skip-6m3-tapat.name",
    descriptionKey: "catalog.containers.skip-6m3-tapat.description",
    useCasesKey: "catalog.containers.skip-6m3-tapat.useCases",
  },
  {
    id: "skip-9m3",
    slug: "skip-9m3",
    category: "contenedores",
    modelPath: "/models/skip-9m3.glb",
    posterPath: "/posters/skip-9m3.webp",
    specs: {
      length: 4000,
      width: 2000,
      height: 1500,
      capacity: "9m³",
      weight: 550,
      material: "Acero",
    },
    nameKey: "catalog.containers.skip-9m3.name",
    descriptionKey: "catalog.containers.skip-9m3.description",
    useCasesKey: "catalog.containers.skip-9m3.useCases",
  },
  {
    id: "skip-9m3-estanc",
    slug: "skip-9m3-estanc",
    category: "contenedores",
    modelPath: "/models/skip-9m3-estanc.glb",
    posterPath: "/posters/skip-9m3-estanc.webp",
    specs: {
      length: 4000,
      width: 2000,
      height: 1500,
      capacity: "9m³",
      weight: 650,
      material: "Acero estanco",
    },
    nameKey: "catalog.containers.skip-9m3-estanc.name",
    descriptionKey: "catalog.containers.skip-9m3-estanc.description",
    useCasesKey: "catalog.containers.skip-9m3-estanc.useCases",
  },
  {
    id: "rolloff-10-13m3",
    slug: "rolloff-10-13m3",
    category: "contenedores",
    modelPath: "/models/rolloff-10-13m3.glb",
    posterPath: "/posters/rolloff-10-13m3.webp",
    specs: {
      length: 5000,
      width: 2200,
      height: 1600,
      capacity: "10-13m³",
      weight: 750,
      material: "Acero",
    },
    nameKey: "catalog.containers.rolloff-10-13m3.name",
    descriptionKey: "catalog.containers.rolloff-10-13m3.description",
    useCasesKey: "catalog.containers.rolloff-10-13m3.useCases",
  },
  {
    id: "rolloff-12m3",
    slug: "rolloff-12m3",
    category: "contenedores",
    modelPath: "/models/rolloff-12m3.glb",
    posterPath: "/posters/rolloff-12m3.webp",
    specs: {
      length: 5500,
      width: 2200,
      height: 1700,
      capacity: "12m³",
      weight: 850,
      material: "Acero",
    },
    nameKey: "catalog.containers.rolloff-12m3.name",
    descriptionKey: "catalog.containers.rolloff-12m3.description",
    useCasesKey: "catalog.containers.rolloff-12m3.useCases",
  },
  {
    id: "rolloff-15-40m3",
    slug: "rolloff-15-40m3",
    category: "contenedores",
    modelPath: "/models/rolloff-15-40m3.glb",
    posterPath: "/posters/rolloff-15-40m3.webp",
    specs: {
      length: 7000,
      width: 2300,
      height: 2000,
      capacity: "15-40m³",
      weight: 1500,
      material: "Acero",
    },
    nameKey: "catalog.containers.rolloff-15-40m3.name",
    descriptionKey: "catalog.containers.rolloff-15-40m3.description",
    useCasesKey: "catalog.containers.rolloff-15-40m3.useCases",
  },
  {
    id: "estancs-15-25m3",
    slug: "estancs-15-25m3",
    category: "contenedores",
    modelPath: "/models/estancs-15-25m3.glb",
    posterPath: "/posters/estancs-15-25m3.webp",
    specs: {
      length: 6000,
      width: 2300,
      height: 1800,
      capacity: "15-25m³",
      weight: 1800,
      material: "Acero estanco",
    },
    nameKey: "catalog.containers.estancs-15-25m3.name",
    descriptionKey: "catalog.containers.estancs-15-25m3.description",
    useCasesKey: "catalog.containers.estancs-15-25m3.useCases",
  },
  {
    id: "confidencial",
    slug: "confidencial",
    category: "contenedores",
    modelPath: "/models/confidencial.glb",
    posterPath: "/posters/confidencial.webp",
    specs: {
      length: 600,
      width: 500,
      height: 900,
      capacity: "80L",
      weight: 20,
      material: "Acero con cerradura",
    },
    nameKey: "catalog.containers.confidencial.name",
    descriptionKey: "catalog.containers.confidencial.description",
    useCasesKey: "catalog.containers.confidencial.useCases",
  },
  // ── MAQUINARIA ───────────────────────────────────────────────────────────
  {
    id: "compactadora",
    slug: "compactadora",
    category: "maquinaria",
    modelPath: "/models/compactadora.glb",
    posterPath: "/posters/compactadora.webp",
    specs: {
      length: 6000,
      width: 2300,
      height: 2500,
      capacity: "20m³",
      weight: 5000,
      material: "Acero",
    },
    nameKey: "catalog.containers.compactadora.name",
    descriptionKey: "catalog.containers.compactadora.description",
    useCasesKey: "catalog.containers.compactadora.useCases",
  },
  {
    id: "autovoltejador",
    slug: "autovoltejador",
    category: "maquinaria",
    modelPath: "/models/autovoltejador.glb",
    posterPath: "/posters/autovoltejador.webp",
    specs: {
      length: 5500,
      width: 2200,
      height: 2200,
      capacity: "Variable",
      weight: 4500,
      material: "Acero",
    },
    nameKey: "catalog.containers.autovoltejador.name",
    descriptionKey: "catalog.containers.autovoltejador.description",
    useCasesKey: "catalog.containers.autovoltejador.useCases",
  },
  {
    id: "autobasculant",
    slug: "autobasculant",
    category: "maquinaria",
    modelPath: "/models/autobasculant.glb",
    posterPath: "/posters/autobasculant.webp",
    specs: {
      length: 5000,
      width: 2200,
      height: 2000,
      capacity: "Variable",
      weight: 3500,
      material: "Acero",
    },
    nameKey: "catalog.containers.autobasculant.name",
    descriptionKey: "catalog.containers.autobasculant.description",
    useCasesKey: "catalog.containers.autobasculant.useCases",
  },
  {
    id: "roll-paker",
    slug: "roll-paker",
    category: "maquinaria",
    modelPath: "/models/roll-paker.glb",
    posterPath: "/posters/roll-paker.webp",
    specs: {
      length: 6500,
      width: 2300,
      height: 2500,
      capacity: "30m³",
      weight: 6000,
      material: "Acero",
    },
    nameKey: "catalog.containers.roll-paker.name",
    descriptionKey: "catalog.containers.roll-paker.description",
    useCasesKey: "catalog.containers.roll-paker.useCases",
  },
  {
    id: "rotocompactador",
    slug: "rotocompactador",
    category: "maquinaria",
    modelPath: "/models/rotocompactador.glb",
    posterPath: "/posters/rotocompactador.webp",
    specs: {
      length: 4500,
      width: 2000,
      height: 2200,
      capacity: "8m³",
      weight: 3000,
      material: "Acero",
    },
    nameKey: "catalog.containers.rotocompactador.name",
    descriptionKey: "catalog.containers.rotocompactador.description",
    useCasesKey: "catalog.containers.rotocompactador.useCases",
  },
  {
    id: "cisterna",
    slug: "cisterna",
    category: "maquinaria",
    modelPath: "/models/cisterna.glb",
    posterPath: "/posters/cisterna.webp",
    specs: {
      length: 6000,
      width: 2200,
      height: 2200,
      capacity: "15000L",
      weight: 4000,
      material: "Acero inoxidable",
    },
    nameKey: "catalog.containers.cisterna.name",
    descriptionKey: "catalog.containers.cisterna.description",
    useCasesKey: "catalog.containers.cisterna.useCases",
  },
];

export function getContainerBySlug(slug: string): Container | undefined {
  return containers.find((c) => c.slug === slug);
}

export function getContainersByCategory(
  category: Container["category"]
): Container[] {
  return containers.filter((c) => c.category === category);
}
